version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
